apiVersion: v1
kind: Service
metadata:
  labels:
    app: site-svc
  name: site-loadbalancer-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fiap-siteeks
  type: LoadBalancer