apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  MONGO_URL: mongodb://ab8f079582e1f4fa786504065df56521-1836127033.us-east-1.elb.amazonaws.com:27017/db_fiap