apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-loadbalancer-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-pod
  type: LoadBalancer
