apiVersion: v1
kind: Pod
metadata:
  name: api-pod-news
  labels:
    app: api-pod-news
spec:
  containers:
    - name: api-pod-config
      image: tadrianonet/apisitek8s
      ports:
        - containerPort: 3000
      env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MONGO_URL