apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc-news
  name: api-loadbalancer-svc-news
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: api-pod-news
  type: LoadBalancer
