name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Check test status
      run: echo "::set-output name=test_failed::$(grep -q 'Test Suites:.*failed' ./test-results.txt && echo true || echo false)"

    - name: Stop on test failure
      if: ${{ steps.check_test_status.outputs.test_failed == 'true' }}
      run: exit 1
